language: node_js

jobs:
  include:
    - stage: npm test
      node_js:
        - "node"
      cache: npm
      services:
        - docker
      before_script:
        - yarn run lint
      script:
        - yarn test

    - stage: npm release
      if: tag IS present
      node_js: "node"
      cache: npm
      script: yarn
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true